name: portfolio
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^6.5.5
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  auto_size_text: ^3.0.0
  universal_html: ^2.2.4
  dio: ^5.3.3
  http: ^1.1.0
  carousel_slider: ^4.2.1
  json_annotation: ^4.8.0
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true