name: On Website Deploy
"on":
  push:
    branches:
      - "master"
jobs:
  build_and_deploy_web:
    name: Build & Deploy Flutter to Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: 🌍 Enable Web
        run: flutter config --enable-web

      - name: 📦 Get packages
        run: flutter pub get

      - name: 🏭 Build Web Application
        run: flutter build web --release

      - name: Make copy of artifacts
        run: |
          chmod u+x "${GITHUB_WORKSPACE}/createandcopytofolder.sh"
          bash "${GITHUB_WORKSPACE}/createandcopytofolder.sh"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit the artifacts.
